### ISSUE TITLE
Fails to Format Date on Specific Browsers

### ISSUE THREAD

**Issue by Feeral** [CardJs/CardJs#35]
Hello,

We are encountering an issue were the date is not being formatted correctly and is triggering an invalid state. The user will enter 1224 and it does not reformat it to 12 / 24. This then triggers and invalid field warning and prevents the user from purchasing.

We have documented 50 errors in the past 30 days. Below is a screen grab of the input field and a sample list of the environment.

Screen grab of formatting failure:
https://www.screencast.com/t/QpSWF4gQ7i5 

**Sample of OS / Browser / Device**

Chrome Mobile 61
Operating System Android 6
Device	Mobile:LG Escape 3

Safari 10
Operating System macOS 10
Device Desktop/Laptop:Apple Macintosh

Kindle-Silk 58
Operating System	Android 5
Device Tablet:Amazon Fire HD 8

Chrome Mobile 61
Operating System	Android 7
Device Mobile:LG Stylo 3 LTE

**Comment by MMrR0b0TT** [comment]
+1

**Comment by ghost** [comment]
I fixed this by modifying the card-js.js source code to set the EXPIRY_USE_DROPDOWNS variable to true.

**Comment by mpopolin** [comment]
Same for me using Samsung devices. Any update on this?
Settigns EXPIRY_USE_DROPDOWNS to true did not fix my issue.

**Comment by gogcwy** [comment]
the same problem with me.
Card Numberr and expiry can not format with space.
this issue cause many samsung mobile customer can not finish payment.
EXPIRY_USE_DROPDOWNS = true can not show dropdown div
who can solve this issue
thanks
